version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
